# WARNING: MySQL doesn't implement CHECK constraints; you have to manually add triggers
# Here the CHECK statements are just for easy reference

CREATE TABLE IF NOT EXISTS CUSTOMER(
	CUSTNO VARCHAR(8) NOT NULL PRIMARY KEY,
	CUSTNAME VARCHAR(30) NOT NULL,
	ADDRESS VARCHAR(50) NOT NULL,
	INTERNAL CHAR(1) NOT NULL,
	CONTACT VARCHAR(30) NOT NULL,
	PHONE VARCHAR(12) NOT NULL,
	CITY VARCHAR(30) NOT NULL,
	STATE VARCHAR(5) NOT NULL,
	ZIP VARCHAR(10) NOT NULL
);

CREATE TABLE IF NOT EXISTS FACILITY(
	FACNO VARCHAR(8) NOT NULL PRIMARY KEY,
	FACNAME VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS EVENTREQUEST(
	EVENTNO VARCHAR(8) NOT NULL PRIMARY KEY,
	DATEHELD DATE NOT NULL,
	DATEREQ DATE NOT NULL,
	CUSTNO VARCHAR(8) NOT NULL,
	FACNO VARCHAR(8) NOT NULL,
	DATEAUTH DATE,
	STATUS VARCHAR(20) NOT NULL CHECK (STATUS IN ('Pending','Denied','Approved')),
	ESTCOST DOUBLE(12,6) NOT NULL,
	ESTAUDIENCE DOUBLE(12,6) NOT NULL CHECK (ESTAUDIENCE > 0),
	BUDNO VARCHAR(10),
	FOREIGN KEY (CUSTNO) REFERENCES CUSTOMER(CUSTNO),
	FOREIGN KEY (FACNO) REFERENCES FACILITY(FACNO)
);


CREATE TABLE IF NOT EXISTS LOCATION(
	LOCNO VARCHAR(8) NOT NULL PRIMARY KEY,
	FACNO VARCHAR(8) NOT NULL,
	LOCNAME VARCHAR(30) NOT NULL,
	FOREIGN KEY (FACNO) REFERENCES FACILITY(FACNO)
);

CREATE TABLE IF NOT EXISTS EMPLOYEE(
	EMPNO VARCHAR(8) NOT NULL PRIMARY KEY,
	EMPNAME VARCHAR(30) NOT NULL,
	DEPARTMENT VARCHAR(30) NOT NULL,
	EMAIL VARCHAR(40) NOT NULL UNIQUE,
	PHONE VARCHAR(12) NOT NULL
);

CREATE TABLE IF NOT EXISTS EVENTPLAN(
	PLANNO VARCHAR(8) NOT NULL PRIMARY KEY,
	EVENTNO VARCHAR(8) NOT NULL,
	WORKDATE DATE NOT NULL,
	NOTES VARCHAR(50),
	ACTIVITY VARCHAR(30) NOT NULL,
	EMPNO VARCHAR(8),
	FOREIGN KEY (EVENTNO) REFERENCES EVENTREQUEST(EVENTNO),
	FOREIGN KEY (EMPNO) REFERENCES EMPLOYEE(EMPNO)
);

CREATE TABLE IF NOT EXISTS RESOURCETBL(
	RESNO VARCHAR(8) NOT NULL PRIMARY KEY,
	RESNAME VARCHAR(30) NOT NULL,
	RATE DOUBLE(12,6) NOT NULL CHECK (RATE > 0)
);

CREATE TABLE IF NOT EXISTS EVENTPLANLINE(
	PLANNO VARCHAR(8) NOT NULL,
	LINENO MEDIUMINT(6) NOT NULL,
	TIMESTART DATETIME NOT NULL,
	TIMEEND DATETIME NOT NULL,
	NUMBERFLD MEDIUMINT(6) NOT NULL,
	LOCNO VARCHAR(8) NOT NULL,
	RESNO VARCHAR(8) NOT NULL,
	PRIMARY KEY (PLANNO, LINENO),
	FOREIGN KEY (PLANNO) REFERENCES EVENTPLAN(PLANNO),
	FOREIGN KEY (LOCNO) REFERENCES LOCATION(LOCNO),
	FOREIGN KEY (RESNO) REFERENCES RESOURCETBL(RESNO),
	CHECK (TIMESTART < TIMEEND)
);




